### ISSUE TITLE
module Responders.Html is not loaded and could not be found

### ISSUE THREAD

**Issue by PavelZX** [klacointe/coherence_spa_example#1]
C:\SIM\coherence_spa_example\server>mix phx.server
Compiling 35 files (.ex)
warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/coherence_spa/coherence/user.ex:11: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paralle
lCompiler.spawn_compilers/1

== Compilation error in file lib/coherence_spa_web/controllers/coherence/respond
ers/html.ex ==
** (CompileError) lib/coherence_spa_web/controllers/coherence/responders/html.ex
:3: module Responders.Html is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/coherence_spa_web/controllers/coherence/responders/html.ex:3: Coherence.
Responders.Html (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.Paral
lelCompiler.spawn_compilers/1

C:\SIM\coherence_spa_example\server>

**Comment by klacointe** [comment]
Better with a valid commit for coherence dependencie?

**Comment by PavelZX** [comment]
Your work is not completed?

**Comment by klacointe** [comment]
Yes, this is a work in progress.
